# Use new trusty images, should yield newer compilers and packages
sudo: required
dist: precise
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5

addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
      - lcov

before_install:
  - sudo apt-get update -qq

script:
  - cmake -DENABLE_COVERAGE=On -DCMAKE_CXX_COMPILER=$COMPILER . && make && make test
  - make gcov
  - make lcov

after_success:
  - bash <(curl -s https://codecov.io/bash) -X gcov